Wonder what species of IRIS do these flowers belong to?

Import the Libraries

In [10]:
# Import the Libraries

# Loading the Library with the iris dataset
from sklearn.datasets import load_iris

# Loading scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

#Loading Pandas & Numpy
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#Setting random seed
np.random.seed(0)

In [11]:
# Creating an Object called iris with iris dataset
iris = load_iris()
iris = pd.DataFrame(iris.data, columns= iris.feature_names)
# df.head()

#from dataset file of iris.csv
# iris = pd.read_csv('Iris.csv')
# Displaying first 5 rows of our dataset
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
# Displaying last five rows of our dataset
iris.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [13]:
# Now we gonna add one column

# Creating Test and Train Data
iris['is_train'] = np.random.uniform(0,1, len(iris)) <=.75

#Displaying the top 5 rows
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   is_train  
0      True  
1      True  
2      True  
3      True  
4      True

In [14]:
# Creating the data frames with test rows and training rows
train, test = iris[iris['is_train'] == True], iris[iris['is_train'] == False]

# Show the number of observation for the test and training data frames
print('Number of observation in the training dataset : ', len(train))
print('Number of observation in the test dataset : ', len(test))

Number of observation in the training dataset :  118
Number of observation in the test dataset :  32


In [15]:
# Creating a list of the Feature column's names
features = iris.columns[1:5]

# View Features
print(features )

Index(['sepal width (cm)', 'petal length (cm)', 'petal width (cm)',
       'is_train'],
      dtype='object')


In [17]:
# Converting each species name into digits
y = pd.factorize(train['is_train'])[0]

#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Creating a Random Forest Classifier
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)

# Training the classifier
print(clf.fit(train[features], y))

RandomForestClassifier(n_jobs=2, random_state=0)


In [19]:
# Applying the trained classifier to the test
test[features]
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[10:20]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [26]:
# Mapping names for the plants for each predicted plant class
preds = iris.is_train[clf.predict(test[features])]


# View the PREDICTED species for the first five observations
preds[0:5]

0    True
0    True
0    True
0    True
0    True
Name: is_train, dtype: bool

In [27]:
# Viewing the Actual species for the first five observations
test['is_train'].head()

7     False
8     False
10    False
13    False
17    False
Name: is_train, dtype: bool

In [28]:
# Create Confusion matrix
# cm  = metrics.confusion_matrix(test['Species'],preds)
# # Visualizing the confusion matrix
# plt.figure(figsize=(9,9))
# sns.heatmap(cm,annot = True, fmt = ".3f", linewidths = .5, square = True, cmap = 'Blues_r')
# plt.ylabel('Actual Label')
# plt.xlabel('Predicted Label')
# # all_sample_title = 'Accuracy Score : {0}'.format(score)
# #plt.title(all_sample_title, size = 15)
# prin
pd.crosstab(test['is_train'], preds, rownames = ['Actual Species'], colnames=['Predicted Species'])

<ipython-input-28-fb306cfcbe2b>:11: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  pd.crosstab(test['is_train'], preds, rownames = ['Actual Species'], colnames=['Predicted Species'])


Empty DataFrame
Columns: []
Index: []

In [30]:
xd = iris.is_train[clf.predict([[5.1,	3.5,	1.4,	0.2],[4.6,	3.1,	1.5,	0.2]])]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [31]:
clf.predict([[5.1,	3.5,	1.4,	0.2],[4.6,	3.1,	1.5,	0.2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0])